name: Testing
on: [pull_request]
jobs:
  standard-checks:
    name: Run unit tests
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        run: npm ci

      - name: Run ESlint
        run: npm run ci:test